/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stm32f411xx.h>
#include <string.h>
#include <stdio.h>


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	GPIO_Handle_t 	GpioTx, GpioRx;
	USART_Handle_t 	Uart;
	uint8_t receive = 0;

	/* Configuration ALT */
	GpioTx.pGPIOx  = GPIOA;
	GpioTx.GPIO_PinConfig.GPIO_PinNumber 		= GPIO_PIN_NO_9;
	GpioTx.GPIO_PinConfig.GPIO_PinMode 			= GPIO_MODE_ALTFN;
	GpioTx.GPIO_PinConfig.GPIO_PinSpeed 		= GPIO_SPEED_FAST;
	GpioTx.GPIO_PinConfig.GPIO_PinOPType 		= GPIO_OP_TYPE_PP;
	GpioTx.GPIO_PinConfig.GPIO_PinPuPdControl 	= GPIO_PIN_PU;
	GpioTx.GPIO_PinConfig.GPIO_PinAltFunMode 	= GPIO_ALTF_7; //0x0111; /* AF07 */

	GpioRx.pGPIOx  = GPIOA;
	GpioRx.GPIO_PinConfig.GPIO_PinNumber 		= GPIO_PIN_NO_10;
	GpioRx.GPIO_PinConfig.GPIO_PinMode 			= GPIO_MODE_ALTFN;
	GpioRx.GPIO_PinConfig.GPIO_PinSpeed 		= GPIO_SPEED_FAST;
	GpioRx.GPIO_PinConfig.GPIO_PinOPType 		= GPIO_OP_TYPE_PP;
	GpioRx.GPIO_PinConfig.GPIO_PinPuPdControl 	= GPIO_PIN_PU;
	GpioRx.GPIO_PinConfig.GPIO_PinAltFunMode 	= GPIO_ALTF_7; //0x0111; /* AF07 */

	GPIO_PeriClockControl(GPIOA, ENABLE);

	GPIO_Init(&GpioTx);
	GPIO_Init(&GpioRx);

	/* Configuration UART: 8bit, no-parity */
	Uart.pUSARTx = USART1;
	Uart.USART_Config.USART_Mode = USART_MODE_TXRX;
	Uart.USART_Config.USART_Baud = USART_STD_BAUD_9600;
	Uart.USART_Config.USART_NoOfStopBits = USART_STOPBITS_1;
	Uart.USART_Config.USART_WordLength = USART_WORDLEN_8BITS;
	Uart.USART_Config.USART_ParityControl = USART_PARITY_DISABLE;
	Uart.USART_Config.USART_HWFlowControl = USART_HW_FLOW_CTRL_NONE;

	UART_set(&Uart);

	while(1) {
		/* Configuration TX */
		UART_TX(&Uart, (uint8_t*)"hi", strlen("hi"));

		/* Configuration TX */
		receive = UART_RX(&Uart);

		printf("receive: %c\n", receive);
	}

}
